live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
# dynamic_title = true
size = 8

[font.normal]
family = "Hack"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Control"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Alt"

[mouse]
hide_when_typing = true

[selection]
semantic_escape_chars = ""

[window]
decorations = "none"
dynamic_padding = false

[window.padding]
x = 20
y = 20
