#!/bin/bash

# Get battery percentage using acpi command
battery_percent=$(acpi -b | awk '{print $4}' | tr -d '%,')

# Output the battery percentage
if [ $battery_percent -eq 100 ]; then
    echo " $battery_percent"
elif [ $battery_percent -gt 80 ]; then
    echo " $battery_percent"
elif [ $battery_percent -gt 50 ]; then
    echo " $battery_percent"
elif [ $battery_percent -lt 40 ]; then
    echo " $battery_percent"
elif [ $battery_percent -lt 20 ]; then
    echo " $battery_percent"
else
    echo ""
fi

