#!/bin/bash

# Get battery percentage using acpi command
battery_percent=$(acpi -b | awk '{print $4}' | tr -d '%,')

# Output the battery percentage
if [ $battery_percent -eq 100 ]; then
    echo " $battery_percent%"
elif [ $battery_percent -ge 80 ]; then
    echo " $battery_percent%"
elif [ $battery_percent -ge 50 ]; then
    echo " $battery_percent%"
elif [ $battery_percent -le 40 ]; then
    echo " $battery_percent%"
elif [ $battery_percent -lt 20 ]; then
    echo " $battery_percent%"
elif [ $battery_percent -le 10 ]; then
    echo "LOW  $battery_percent%"
fi

